name: media
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.* #  - libstdcxx-ng # Bug fix for "Cannot load `swrast` and `iris` drivers"
  - gstreamer
  - gst-plugins-good
  - gst-libav
  - numpy
  - opencv
  - pillow
  - pyqt
  - pyqtwebengine # bro
  - piexif
  - send2trash
  - tzwhere # this is to correct utc to correct timezone in case of QuickTime videos
  - pytz
  - pip
  - pip:
      - moviepy # Bug with func if using conda version
      - pyheif
