name: media
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - numpy
  - opencv
  - pillow
  - pyqt
  - pyqtwebengine # bro
  - piexif
  - send2trash
  - tzwhere # this is to correct utc to correct timezone in case of QuickTime videos
  - pytz
  - pip
  - pip:
      - pyheif
