name: media-manager # you probably want to 'snapcraft register <name>'

summary: A media manager with basic functionalities  # 79 char long summary
description: A simple media manager with renaming, localization and other functionalities
version: git
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode #devmode # use 'strict' once you have the right plugs and slots
base: core20 # the base snap is the execution environment for this snap
architectures:
  - build-on: [amd64]
apps:
  media-manager:
    command: bin/pdtk
    plugs:
      - home
      - desktop
      - removable-media
      - network

parts:
  media-manager:
    plugin: conda
    conda-miniconda-version: 4.11.0
    source: .
    conda-packages:
      - -c
      - conda-forge
      - pandoc
#  media-manager:
#    plugin: python
#    source-type: git
#    source: https://github.com/ericj974/media_manager.git

