name: movie_player
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.* #  - libstdcxx-ng # Bug fix for "Cannot load `swrast` and `iris` drivers"
  - gstreamer
  - gst-plugins-good
  - gst-libav
  - pyqt
